In [19]:
produtos = []
qtde_total = []
produto_qt = []
produto = "i"

while produto != "":
    print("SISTEMA DE SUPERMERCADO")
    produto = input("Digite o nome do produto: ")
    qtde = (input("Digite quantidade"))
    produto_qt.append(f"Produto: {produto} || quantidade vendida: {qtde}")
    
print(produto_qt)

SISTEMA DE SUPERMERCADO
Digite o nome do produto: pao
Digite quantidade12
SISTEMA DE SUPERMERCADO
Digite o nome do produto: pao
Digite quantidade0
SISTEMA DE SUPERMERCADO
Digite o nome do produto:
Digite quantidade
['Produto: pao || quantidade vendida: 12', 'Produto: pao || quantidade vendida: 0', 'Produto:  || quantidade vendida: ']

In [42]:

vendas = [941, 852, 783, 714, 697, 686, 685, 670, 631, 453, 386, 371, 294, 269, 259, 218, 208, 163, 125, 102, 87, 47, 7]

vendedores = ['Maria', 'José', 'Antônio', 'João', 'Francisco', 'Ana', 'Luiz', 'Paulo', 'Carlos', 'Manoel', 'Pedro', 'Francisca', 'Marcos', 'Raimundo', 'Sebastião', 'Antônia', 'Marcelo', 'Jorge', 'Márcia', 'Geraldo', 'Adriana', 'Sandra', 'Luis']
meta = 50

for venda in vendas:
    d = vendas.index(venda)    
    c = vendedores[d]
    b = vendas[d]
       
    if venda >= meta:
        print(f"vendedor {c}\nVendas {b}")

vendedor Maria
Vendas 941
vendedor José
Vendas 852
vendedor Antônio
Vendas 783
vendedor João
Vendas 714
vendedor Francisco
Vendas 697
vendedor Ana
Vendas 686
vendedor Luiz
Vendas 685
vendedor Paulo
Vendas 670
vendedor Carlos
Vendas 631
vendedor Manoel
Vendas 453
vendedor Pedro
Vendas 386
vendedor Francisca
Vendas 371
vendedor Marcos
Vendas 294
vendedor Raimundo
Vendas 269
vendedor Sebastião
Vendas 259
vendedor Antônia
Vendas 218
vendedor Marcelo
Vendas 208
vendedor Jorge
Vendas 163
vendedor Márcia
Vendas 125
vendedor Geraldo
Vendas 102
vendedor Adriana
Vendas 87

In [43]:
vendas = [122, 300, 800, 1500, 1900, 2750, 400, 20 , 23, 70, 90, 80, 1100, 999, 880, 870, 50, 1111, 120, 300, 540, 800]
meta = 1000
for venda in vendas:
    if venda >= meta:
        print(venda)

1500
1900
2750
1100
1111

In [44]:
vendedores = ['joão', 'lucas', 'thiago', 'maria', 'josé', 'jorge']
vendas = [122, 300, 800, 1500, 16000, 89600]
meta = 1000
f = 0

for venda in vendas:
    if venda >= meta:
        i = vendas.index(venda)
        y = vendedores[i]
        u = vendas[i]
        f = f + 1
        print(f"Parabéns {y} você atingiu a meta com um total de R${u}")
print(f"Total de funcioários que atingiram a meta = {f}")

Parabéns maria você atingiu a meta com um total de R$1500
Parabéns josé você atingiu a meta com um total de R$16000
Parabéns jorge você atingiu a meta com um total de R$89600
Total de funcioários que atingiram a meta = 3

In [ ]:
alunos = []
presentes = []
a = 0
faltosos = []
f = 0

for aluno in range(3):
    nome = input(str("Nome do Aluno: "))
    alunos.append(nome)
    presença = input(str("F = Faltasos/ P = Presentes: "))
    if (nome in alunos) and (presença == "p") or (presença == "P"):
        a = a + 1
        presentes.append(nome)
    if (nome in alunos) and (presença == "f") or (presença == "F"):
        f = f - 1
        faltosos.append(nome)
print(alunos)
print(f"Total de alunos = {len(alunos)}")
print("-----------------------------------------------------------------------------------------------------------------------")
print(f"Alunos presentes = {presentes}")
print(f"Total de alunos presentes = {a}")
print("-----------------------------------------------------------------------------------------------------------------------")
print(f"Alunos faltosos = {faltosos}")
print(f"Total de alunos faltosos = {f}")
print("-----------------------------------------------------------------------------------------------------------------------")

In [ ]:
vendedores = ['joão', 'lucas', 'thiago', 'maria', 'josé', 'jorge']
vendas = [122, 300, 800, 1500, 16000, 89600]
    
for melhor in vendedores:
    m = max(vendas)
    i = vendas.index(m)
    o = vendedores[i]
print(f"O melhor funcionário do mês foi {o}, com um total de R${m}")

In [ ]:
lista = ['goiaba', 'abacaxi', 'maça', 'uva', 'peira', 'maracuja', 'limçao', 'cupuaçu']
s = "S"
n = "N"
i = 0 
for frutas in lista:
    f = input(str(f"O item {lista[i]} é uma fruta? S/N: "))
    if f == s:
        print("OK! Confira o restante")
        i = i + 1
    elif f == n:
        print("OK! Confira o restante")
        i = i + 1
    elif f != s or f != n:
        break

In [ ]:
qt_hospedes = int(input("Digite a quantidade de hóspedes: "))
quarto = []

if qt_hospedes <= 4:
    for pessoas in range(qt_hospedes):
        nome = input(str("Digite o nome do hóspede: "))
       
        c = int(input("Digite seu CPF: "))
        hospedes = ["Nome: {}".format(nome), "CPF: {}".format(c)]
        quarto.append(hospedes)
        print(quarto) 
else:
    print("Erro! nossos quartos só suportam ate 4 pessoas.")

In [ ]:
pergunta = "S"

while pergunta != "N":
    pergunta = input(str("Deseja continuar o programa (S/N): "))

In [58]:
for o in range(11):
    for i in range(11):
        print(f"{o} x {i} = {o * i}\n")

0 x 0 = 0

0 x 1 = 0

0 x 2 = 0

0 x 3 = 0

0 x 4 = 0

0 x 5 = 0

0 x 6 = 0

0 x 7 = 0

0 x 8 = 0

0 x 9 = 0

0 x 10 = 0

1 x 0 = 0

1 x 1 = 1

1 x 2 = 2

1 x 3 = 3

1 x 4 = 4

1 x 5 = 5

1 x 6 = 6

1 x 7 = 7

1 x 8 = 8

1 x 9 = 9

1 x 10 = 10

2 x 0 = 0

2 x 1 = 2

2 x 2 = 4

2 x 3 = 6

2 x 4 = 8

2 x 5 = 10

2 x 6 = 12

2 x 7 = 14

2 x 8 = 16

2 x 9 = 18

2 x 10 = 20

3 x 0 = 0

3 x 1 = 3

3 x 2 = 6

3 x 3 = 9

3 x 4 = 12

3 x 5 = 15

3 x 6 = 18

3 x 7 = 21

3 x 8 = 24

3 x 9 = 27

3 x 10 = 30

4 x 0 = 0

4 x 1 = 4

4 x 2 = 8

4 x 3 = 12

4 x 4 = 16

4 x 5 = 20

4 x 6 = 24

4 x 7 = 28

4 x 8 = 32

4 x 9 = 36

4 x 10 = 40

5 x 0 = 0

5 x 1 = 5

5 x 2 = 10

5 x 3 = 15

5 x 4 = 20

5 x 5 = 25

5 x 6 = 30

5 x 7 = 35

5 x 8 = 40

5 x 9 = 45

5 x 10 = 50

6 x 0 = 0

6 x 1 = 6

6 x 2 = 12

6 x 3 = 18

6 x 4 = 24

6 x 5 = 30

6 x 6 = 36

6 x 7 = 42

6 x 8 = 48

6 x 9 = 54

6 x 10 = 60

7 x 0 = 0

7 x 1 = 7

7 x 2 = 14

7 x 3 = 21

7 x 4 = 28

7 x 5 = 35

7 x 6 = 42

7 x 7 = 49

7 x 8 = 56

7 x 9 = 63

7 x 10 = 70

8 x 0 = 0

8 x 1 = 8

8 x 2 = 16

8 x 3 = 24

8 x 4 = 32

8 x 5 = 40

8 x 6 = 48

8 x 7 = 56

8 x 8 = 64

8 x 9 = 72

8 x 10 = 80

9 x 0 = 0

9 x 1 = 9

9 x 2 = 18

9 x 3 = 27

9 x 4 = 36

9 x 5 = 45

9 x 6 = 54

9 x 7 = 63

9 x 8 = 72

9 x 9 = 81

9 x 10 = 90

10 x 0 = 0

10 x 1 = 10

10 x 2 = 20

10 x 3 = 30

10 x 4 = 40

10 x 5 = 50

10 x 6 = 60

10 x 7 = 70

10 x 8 = 80

10 x 9 = 90

10 x 10 = 100